"""init database

Revision ID: 08f8210958c5
Revises: 5d8ca04ed895
Create Date: 2025-04-16 21:47:07.116998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f8210958c5'
down_revision: Union[str, None] = '5d8ca04ed895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game-story-acts', sa.Column('number', sa.Integer(), nullable=False))
    op.add_column('game-story-acts', sa.Column('is_final_act', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game-story-acts', 'is_final_act')
    op.drop_column('game-story-acts', 'number')
    # ### end Alembic commands ###
