"""init database

Revision ID: 51496bcb58af
Revises: 42990011e70b
Create Date: 2025-04-22 19:27:20.759812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51496bcb58af'
down_revision: Union[str, None] = '42990011e70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game-sessions', sa.Column('final_video_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game-sessions', 'final_video_url')
    # ### end Alembic commands ###
