"""init database

Revision ID: 5d8ca04ed895
Revises: a89a0a1445a0
Create Date: 2025-04-13 19:53:46.443940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d8ca04ed895'
down_revision: Union[str, None] = 'a89a0a1445a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game-story-acts', sa.Column('prologue', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('game-story-acts', sa.Column('opening_video_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game-story-acts', 'opening_video_url')
    op.drop_column('game-story-acts', 'prologue')
    # ### end Alembic commands ###
