"""init database

Revision ID: a89a0a1445a0
Revises: 
Create Date: 2025-04-11 21:50:40.122268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a89a0a1445a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game-sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tone', sa.Text(), nullable=False),
    sa.Column('world_setting', sa.Text(), nullable=False),
    sa.Column('scenario_overview', sa.Text(), nullable=False),
    sa.Column('raw_events', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_characters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_possible_endings', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_event_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game-story-acts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('overview', sa.String(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('next_act_id', sa.Integer(), nullable=True),
    sa.Column('raw_dialogue', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('photo_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_post_photo_dialogue', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['next_act_id'], ['game-story-acts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game-sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game-story-acts')
    op.drop_table('game-sessions')
    # ### end Alembic commands ###
