"""init database

Revision ID: f6c0d2ad8058
Revises: 
Create Date: 2025-04-25 00:02:25.369986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6c0d2ad8058'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game-sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synopsis', sa.String(), nullable=False),
    sa.Column('visual_style', sa.String(), nullable=False),
    sa.Column('promo_image_url', sa.String(), nullable=False),
    sa.Column('reference_material_summary', sa.Text(), nullable=False),
    sa.Column('opening_video_url', sa.String(), nullable=False),
    sa.Column('opening_act_synopsis', sa.Text(), nullable=False),
    sa.Column('middle_act_synopsis', sa.Text(), nullable=False),
    sa.Column('final_act_synoposis', sa.Text(), nullable=True),
    sa.Column('raw_characters', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('prologue', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remaining_actions', sa.Integer(), nullable=False),
    sa.Column('total_actions', sa.Integer(), nullable=False),
    sa.Column('final_video_url', sa.String(), nullable=True),
    sa.Column('closing_remarks', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game-story-blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('previous_action', sa.String(), nullable=False),
    sa.Column('actions_consumed', sa.Integer(), nullable=False),
    sa.Column('is_final_act', sa.Boolean(), nullable=False),
    sa.Column('dialogue', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('backdrop_image_url', sa.String(), nullable=True),
    sa.Column('possible_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game-sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game-story-blocks')
    op.drop_table('game-sessions')
    # ### end Alembic commands ###
